### ISSUE TITLE
moved* is not redirecting

### ISSUE THREAD

**Issue by danieljsummers** [xyncro/freya-machines#4]
In doing some testing (4.0.0-alpha-170404), it appears that `movedPermanently` and `movedTemporarily` are not producing redirects.  To reproduce, use the current `dotnet new freya -lang F#` and replace `Api.fs` with the following:

```fsharp
module Api

open Freya.Core
open Freya.Machines.Http
open Freya.Optics.Http
open Freya.Routers.Uri.Template
open Freya.Types.Http
open Freya.Types.Uri

let redirectedMachine =
  freyaMachine {
    methods GET
    handleOk (Represent.text "you got redirected!")
    }

let redirectMe =
  freya {
    let location = Location <| Uri (Uri.parse "http://localhost:5000/redirected")
    do! Freya.Optic.set Response.Headers.location_ (Some location)
    return true
    }

let redirectMachine =
  freyaMachine {
    methods GET
    movedPermanently redirectMe // does not work
    //movedTemporarily redirectMe // does not work
    //seeOther redirectMe // works
    }

let root =
  freyaRouter {
    resource "/redirected" redirectedMachine
    resource "/"           redirectMachine
    }
```

The `seeOther` returns a 303, but both `moved`s return zero-length 200 response (with no location header).

**Comment by neoeinstein** [comment]
Sorry for delay in the reply.

You want to do the actual redirect set up in "handleMovedPermanently". According to the [HTTP decision tree for a `GET`](https://docs.freya.io/en/latest/_static/components.getorhead.html), you will also want to set `exists` to `false`. `seeOther` works because it is a part of the ["other" group of specifications](https://docs.freya.io/en/latest/_static/specifications.responses.html), which gets hit if `exists` is `true`.

```fsharp
let redirectedMachine =
  freyaMachine {
    methods GET
    handleOk (Represent.text "you got redirected!")
    }

let handleRedirect =
  freya {
    let location = Location <| Uri (Uri.parse "http://localhost:5000/redirected")
    do! Freya.Optic.set Response.Headers.location_ (Some location)
    return Representation.empty
    }

let redirectMachine =
  freyaMachine {
    methods GET
    exists false
    movedPermanently true
    handleMovedPermanently handleRedirect
    }

let root =
  freyaRouter {
    resource "/redirected" redirectedMachine
    resource "/"           redirectMachine
    }
```

**Comment by danieljsummers** [comment]
OK - I think `exists false` is really the key.  I'm still learning to read those graphics.  :)

I had a much longer reply typed out, and every time I thought I was ready, I kept thinking of other things.  If I get it together and still need help, I'll hit you all up on Gitter or Slack.  (How I came about this is that I have a machine that can accept both `GET` and `HEAD` requests.  For `GET`s, it will redirect, but for `HEAD`s, it will just return OK.  I need to figure out how to distinguish between `exists false` meaning "it's a `GET`"/"do the redirect" or "nothing here".)

Thanks for the help!

**Comment by ibnuda** [comment]
@danieljsummers, I had the same problem as you. Here's what I did.
```
let onlyaccepthead  =
  freya {
    let! meth = Freya.Optic.get Request.method_
    return!
      match meth with
      | Http.Method.HEAD     -> Freya.init true
      | _                    -> Freya.init false
  }

let handleRedirect =
  freya {
    let location = Location <| Uri (Uri.parse "http://localhost:5000/redirected")
    do! Freya.Optic.set Response.Headers.location_ (Some location)
    return Representation.empty
  }

let redirectMachine =
  freyaMachine {
    methods GET
    exists onlyaccepthead
    movedPermanently true
    handleMovedPermanently handleRedirect
  }
```

**Comment by danieljsummers** [comment]
@ibnuda Thanks for that.  I've got an interesting algorithm, at least in its current state.  The URL I'm handling has a "series" and an "episode".

- if the series does not exist in the database, I should return a 404
- else, record a click for the series episode, then
    - if the request is GET, redirect to the episode
    - else (request is HEAD) return an empty OK

I'm currently setting `exists` to the not of the result of the first `if` and setting `seeOther` to the result of the second `if`.  The default handlers do the rest.  Now, I could easily return `false` for both the 404 condition **and** the GET condition; but, if I turn around and set `movedPermanently` true for all GET requests, I'm masking the 404, which would mean I'd generate a redirect for a URL on an unknown series.  Where it should fail, it would pass.

So, how do I distinguish between these conditions without doing a database lookup in both the "does this exist" and "is this moved" decisions?  That's where my thoughts are fuzzy.  And, is `seeOther` actually the right thing to be doing in this case?  In that case, this code is done.  :)

Here is how it's currently structured (some stuff remove for brevity, and this one is still using `seeOther`).

```fsharp
  /// If this returns true, the click was recorded successfully; if not, we did not find the series specified
  let recordClick =
    freya {
      let! seriesId, theEpisode = seriesAndEpisode // gets the parameters from the URL via optics
      match (* [ db lookup for series ] *) with
      | Some _ ->
          // [ record the click ]
          return true
      | _ -> return false
      }

  /// Shorthand to redirect to a URI
  let redirectToUri uri =
    freya {
      let location = Location <| Uri (Uri.parse uri)
      do! Freya.Optic.set Response.Headers.location_ (Some location)
    }
  
  /// Determine if the request is a certain method
  let isMethod (httpMethod : Method) =
    freya {
      let! theMethod = Freya.Optic.get Request.method_
      return theMethod = httpMethod
      }
  
  /// Should we redirect to the episode URL?
  let shouldRedirectToEpisode =
    freya {
      let! isGet = isMethod GET
      match isGet with
      | true ->      
          let! _, link = seriesAndEpisode
          do! redirectToUri (sprintf "http://%s" link)
      | _ -> ()
      return isGet
    }

  /// The machine to handle click URLs
  let machine =
    freyaMachine {
      methods [ HEAD; GET ]
      exists recordClick
      seeOther shouldRedirectToEpisode
      cors
      }
```
